# = = = = = Production Image = = = = =
FROM gcr.io/distroless/static:latest

# TARGETARCH can be "amd64" or "arm64"
ARG TARGETARCH

# - - - - -
COPY --chmod=0755 ./build/hysteria-linux-${TARGETARCH} /usr/bin/hysteria

# - - - - -
ENTRYPOINT ["/usr/bin/hysteria"]
